import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "../globals.css";
import TopBar from "@/components/header/TopBar";
import MainHead from "@/components/header/MainHead";
import MainNav from "@/components/header/MainNav";
import Footer from "./Footer";
import Providers from "@/components/Providers";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={urbanist.className}>
        <Providers>
          <header>
            <TopBar />
            <MainHead />
          </header>
          <MainNav />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
